/**
 * Allowed expense categories.
 * Extend this union as needed — it maps 1-to-1 with the DB CHECK constraint.
 */
export type ExpenseCategory =
  | "Food & Dining"
  | "Transportation"
  | "Housing"
  | "Entertainment"
  | "Healthcare"
  | "Shopping"
  | "Education"
  | "Other";

export const EXPENSE_CATEGORIES: ExpenseCategory[] = [
  "Food & Dining",
  "Transportation",
  "Housing",
  "Entertainment",
  "Healthcare",
  "Shopping",
  "Education",
  "Other",
];

/**
 * Full expense record as stored in Supabase.
 */
export interface Expense {
  id: string;
  category: ExpenseCategory;
  amount: number;
  description: string;
  created_at: string; // ISO 8601 string from Postgres
}

/**
 * Payload used when creating a new expense.
 * `id` and `created_at` are generated by the database.
 */
export interface CreateExpenseInput {
  category: ExpenseCategory | "";
  amount: string; // kept as string for form handling; validated before DB write
  description: string;
}

/**
 * Validation error map — one optional message per field.
 */
export type ExpenseValidationErrors = Partial<
  Record<keyof CreateExpenseInput, string>
>;
